### ISSUE TITLE
Setup initial project

### ISSUE THREAD

**Issue by JoaquimLey** [JoaquimLey/bus-eta#10]
## Why 🤔 

- Since the original project has become quite stale and the idea now is to develop this with the [Twitch Stream](http://twitch.tv/joaquimley) there is a need to do the initial setup again.

# Tasks ⚙️ 

- [x] Initial project setup

- [x] Use versions.gradle configuration

- [x]  Initial project scaffold

- [x] Include initial dependencies (AAC/D2/ETC)
