### ISSUE TITLE
Update readme with stream changelog, roadmap project and stream reference

### ISSUE THREAD

**Issue by JoaquimLey** [JoaquimLey/bus-eta#16]
Since this project will mostly be developed on the stream makes sense to add each step (link) to the readme. Also, some reference to the stream helps

- [x] Create changelog section

- [x] Add the latest stream to the changelog section

- [x] Add stream (and other social) links
