### ISSUE TITLE
Favorites list UI

### ISSUE THREAD

**Issue by JoaquimLey** [JoaquimLey/bus-eta#18]
In order to facilitate the user, we should add the ability to save _favorite_ stations. Depends on #17

- Make it easy UX-wise to make these same favorite requests (MD2.0).

## Tasks ⚙

- [ ] Convert to dynamic feature module

  https://proandroiddev.com/dynamic-feature-module-android-ondemand-module-android-app-bundle-ea0d872b32d

- [ ] Display fetched favorites on the list depends on -> #13 

- [ ] Ability to add a favorite to the favorites list

- [ ] Ability to remove a favorite

----------------------
- [ ] Instrumentation tests

- [ ] Unit tests

**Comment by JoaquimLey** [comment]
Just a reference to the UI-Tests when developing this issue: https://stackoverflow.com/questions/49833533/how-to-correctly-mock-viewmodel-on-androidtest
