### ISSUE TITLE
MVP: Write initial test cases

### ISSUE THREAD

**Issue by JoaquimLey** [JoaquimLey/bus-eta#29]
Currently, there is zero coverage.

## Why

For the initial setup and basic functionally (mostly on stream), no tests were written, but the goal is to have a fully tested app. This will also enable the full power of having a CI/CD pipeline (#19).

## Tasks ⚙️

- [x] Initial setup (dependencies and example tests running)

- [ ] Instrumentation `FavoritesFragment`
- [ ] Unit tests for `FavoritesViewModel`
- [ ] Unit tests for `SmsController`
- [ ] Unit tests for `SmsBroadcastReceiver`
- [ ] Integration tests (UI -> ViewModel + ViewModel -> SMSController)

- [ ] Integrate with some `codecov` like service for overview
     - [ ] Be sure to properly configure (ignore unwanted files to provide accurate %)

--------------------------------

### Resources and references

- A nice gist on how to write good Unit tests https://github.com/dbacinski/Android-Testing-With-Kotlin/blob/master/docs/Unit-Testing-Introduction.md

- Spek http://spekframework.org/

- Kotlin: Using (Test) Robots to make Espresso (kotlin DSL) https://proandroiddev.com/kotlin-using-test-robots-to-make-espresso-8cec2d746973
