### ISSUE TITLE
Migrate to Jetpack

### ISSUE THREAD

**Issue by JoaquimLey** [JoaquimLey/bus-eta#50]
With all the new sugary things announced at I/O'18, this is the perfect playground project to test things.

## Context

This will provide way cleaner APIs and dependencies, unifying the maven paths, testing the 28-alpha versions etc.

## Tasks ⚙️

- [x] Go to -> https://developer.android.com/jetpack/
- [x] Migrate all the necessary dependencies being used
- [x] Update and cleanup `build.gradle`, `versions.gralde`

## UI 🎨

- Migrate app theme to Material theme
    - https://github.com/material-components/material-components-android/blob/master/docs/getting-started.md

    - style="@style/Widget.MaterialComponents.TextInputLayout.OutlineBox"

    - https://github.com/material-components/material-components-android/tree/master/demos

- Bottom sheet modal
    - https://medium.com/halcyon-mobile/implementing-googles-refreshed-modal-bottom-sheet-4e76cb5de65b

## Moareee

_These will have new separate issues._

- Want to try out the `WorkManager` to post sms tasks to the background
    - https://developer.android.com/topic/libraries/architecture/adding-components#workmanager

- Also look into the ThreadPool for other tasks:
  - https://developer.android.com/training/multiple-threads/create-threadpool#ThreadPool
       - See Also: https://developer.android.com/reference/android/app/IntentService

- Look into App bundle
  - https://developer.android.com/guide/app-bundle/build
